
name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
          node-version: '16'

      # Runs a set of commands using the runners shell
      - name: Build
        run: npm i && npm run build && ls

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: dist
          # Destination path
          path: ./dist
